#!/bin/bash
#SBATCH --job-name=stagflow
#SBATCH --partition=short
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=32
#SBATCH --time=04:00:00
#SBATCH --account=eafeerc
#SBATCH --output=regout
#SBATCH --error=regerr

srun -n 128 ./*.ex inputs
