#!/bin/bash
#SBATCH --job-name=regtestcpu
#SBATCH --partition=short
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --time=04:00:00
#SBATCH --account=biocon
#SBATCH --output=regout
#SBATCH --error=regerr

source ~/loadcuda.sh
export MFLO_HOME=/projects/biocon/mesoflow/
export AMREX_HOME=/home/hsitaram/gitrepos/ECP_codes/amrex
. ./script_reg_testing.sh 32 srun ~/ytenv.sh /scratch/hsitaram/mesobio/mesoflow/tests/mflo_results_cpu "DEBUG=TRUE"
