AMREX_HOME ?= ../../../../..

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE

USE_SEC_ORDER_FLUX=TRUE
USE_IMM_BOUNDARY=TRUE

Bpack   := ./Make.package 
Blocs   := . 

include ${CFLO_HOME}/test/Make.cflo
