PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE
USE_HYPRE  = TRUE

Bpack   := ./Make.package 
Blocs   := . 


include ../../tests/Make.mflo
