PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM       = 3

COMP	   = cray

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE
USE_HYPRE  = TRUE

Bpack   := ./Make.package 
Blocs   := . 

HYPRE_DIR=/home/hsitaram/codes/echemAMR/hypre/src/hypre/

include ${MFLO_HOME}/tests/Make.mflo
