#ifndef _MFLO_CONSTANTS_H_
#define _MFLO_CONSTANTS_H_

#define zeroval 0.0
#define one 1.0
#define two 2.0
#define three 3.0
#define four 4.0
#define five 5.0
#define two3rd 0.6666666666666666667
#define half 0.5
#define eighth 0.125
#define sixteenth 0.0625
#define twelveth 0.08333333333
#define fourth 0.25
#define tenth 0.1
#define threetenth 0.3
#define threefourth 0.75
#define N_A 6.02214076e23
#define K_B 1.380649e-23
#define RU 8.31446261815324 //J/K/mol
#define PI 3.14159265358979323846264338327950288
#define P_NTP 101325.0 //pressure at normal pressure and temperature
#define T_NTP 293.15  //temperature at normal pressure and temperature
#define TINYVAL 1e-20
#endif
