name: CI_mesoflow                                                                                                                                        
on: 
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  cputest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: System Dependencies
      run: | 
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        build-essential g++ gfortran libopenmpi-dev openmpi-bin
        git clone https://github.com/AMReX-Codes/amrex
    - name: Build Regression
      working-directory: ./tests
      run: |
        cd Channel
        make -j 2 COMP=gnu DEBUG=TRUE
        cd ..
        cd ShockTube_N2 
        make -j 2 COMP=gnu DEBUG=TRUE
        cd ..
        cd ShockTube_N2He
        make -j 2 COMP=gnu DEBUG=TRUE
        cd ..
        cd SpeciesEqTests 
        make -j 2 COMP=gnu DEBUG=TRUE
        cd ..
        cd TaylorGreen 
        make -j 2 COMP=gnu DEBUG=TRUE
    - name: Run Regression
      working-directory: ./tests
      run: |
          cd Channel
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_x
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_y
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_z
          cd ..
          cd ShockTube_N2
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_x
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_y
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_z
          cd ..
          cd ShockTube_N2He
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_x
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_y
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_z
          cd ..
          cd SpeciesEqTests 
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_x
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_y
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs_z
          cd ..
          cd TaylorGreen 
          mpirun -n 2 ./mesoflow3d.gnu.DEBUG.MPI.ex inputs
  gputest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: System Dependencies
      run: | 
          export DEBIAN_FRONTEND=noninteractive
          wget -q -O - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | sudo apt-key add -
          echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" | sudo tee /etc/apt/sources.list.d/cuda.list
          echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" | sudo tee /etc/apt/sources.list.d/nvidia-ml.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          g++ gfortran libopenmpi-dev openmpi-bin cuda-command-line-tools-11-1 \
          cuda-compiler-11-1 cuda-minimal-build-11-1 \
          cuda-nvml-dev-11-1 cuda-nvtx-11-1 libcurand-dev-11-1 cuda-cupti-dev-11-1
          git clone https://github.com/AMReX-Codes/amrex
    - name: Build Regression
      working-directory: ./tests
      run: |
        export PATH=/usr/local/nvidia/bin:/usr/local/cuda-11.1/bin:${PATH}
        export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda-11.1/lib:${LD_LIBRARY_PATH}
        cd Channel
        make -j 2 COMP=gnu USE_CUDA=TRUE
        cd ..
        cd ShockTube_N2 
        make -j 2 COMP=gnu USE_CUDA=TRUE
        cd ..
        cd ShockTube_N2He
        make -j 2 COMP=gnu USE_CUDA=TRUE
        cd ..
        cd SpeciesEqTests 
        make -j 2 COMP=gnu USE_CUDA=TRUE
        cd ..
        cd TaylorGreen 
        make -j 2 COMP=gnu USE_CUDA=TRUE
